on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check.outputs.changed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Check version changes
        uses: gabriel-gn/hello-world-github-action@v1.0.1
        with:
          filepath: 'design-system/projects/components/package.json'
          packageName: '@mprisma/components'
        id: check # Usa o output checked a partir desse id
      - name: Version checked
        run: 'echo "Version -> ${{ steps.check.outputs.changed }}"'
      - name: Version update detected
        if: |
          steps.check.outputs.changed == 'true'
        run: 'echo "Versão alterada, será criada uma nova release no npm!"'
      - name: Version update not detected
        if: |
          steps.check.outputs.changed == 'false'
        run: 'echo "Versão de pacote não alterada, não será publicado no npm!"'

  publish:
    needs: check-version
    runs-on: ubuntu-latest
    if: |
      needs.check-version.outputs.changed == 'true'
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies and build package
        working-directory: ./design-system
        run: |
          echo "*** Iniciando NPM Install ***"
          npm install
          echo "*** Iniciando NPM RUN BUILD-NPM ***"
          npm run build-npm

      - name: Publish package to NPM
        working-directory: ./design-system
        run: |
          npm run deploy-npm
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
