on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check.outputs.changed }}
    steps:
      - name: Checkout repository
        working-directory: ./design-system
        uses: actions/checkout@v1
      - name: Check version changes
        working-directory: ./design-system/projects/components
        uses: EndBug/version-check@v2.0.1 # https://github.com/marketplace/actions/version-check
        id: check # This will be the reference for later
      - name: Version update detected
        if: |
          steps.check.outputs.changed == 'true'
        run: 'echo "Version change! -> ${{ steps.check.outputs.type }}"'

  publish:
    needs: check-version
    runs-on: ubuntu-latest
    if: |
      needs.check-version.outputs.changed == 'true'
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies and build package
        working-directory: ./design-system
        run: |
          echo "*** Iniciando NPM Install ***"
          npm install
          echo "*** Iniciando NPM RUN BUILD-NPM ***"
          npm run build-npm

      - name: Publish package to NPM
        working-directory: ./design-system
        run: |
          npm run deploy-npm
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
